apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .hosts.grafana }}
    secretName: grafana-tls
  rules:
  - host: {{ .hosts.grafana }}
    http:
      paths:
      - backend:
          serviceName: prometheus-operator-grafana
          servicePort: 80
